---
# tasks file for actions-runner-controller
- name: Check if actions-runner-controller is already Installed
  shell: "helm list --all-namespaces | grep -we {{ namespace }} | grep actions-runner-controller | wc -l"
  register: helm_status

- name: Helm Status
  debug:
   msg: "{% if helm_status.stdout == 1 %} Failed !! - actions-runner-controller is already Installed!{% else %} actions-runner-controller is not Installed !!{% endif %}"
  failed_when: helm_status.stdout == "1"

- name: Add Helm Repo
  command: helm repo add actions-runner-controller https://actions-runner-controller.github.io/actions-runner-controller

- name: Upgrade Helm Repo
  command: helm repo update

- name: Install actions-runner-controller with CRD's
  script: "helm.sh {{ namespace }}"
  register: helm_install_status

- name: Helm Installation Log
  debug: 
    msg: "{{ helm_install_status }}"
